CREATE DATABASE WINDOWS_SERVICES_MONITOR;
GO

USE WINDOWS_SERVICES_MONITOR;
GO

CREATE TABLE SERVERS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ADRESS NVARCHAR(255) NOT NULL,
    STATUS NVARCHAR(50) NOT NULL,
    ENABLED NVARCHAR(10) NOT NULL,
    REGISTER DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE SERVICES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    DESCRIPTION NVARCHAR(50) NOT NULL,
    STATUS NVARCHAR(50) NOT NULL,
    ENABLED NVARCHAR(10) NOT NULL,
    REGISTER DATETIME NOT NULL DEFAULT GETDATE(),
    ID_SERVER INT NOT NULL,
    FOREIGN KEY (ID_SERVER) REFERENCES SERVERS(ID)
);
GO

CREATE TABLE ACTIONS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    DESCRIPTION NVARCHAR(7) NOT NULL  
	    CHECK(DESCRIPTION IN('RUN','STOP','RESTART')),
    STATUS NVARCHAR(50) NOT NULL DEFAULT 'WAITING'
        CHECK (STATUS IN ('WAITING', 'EXECUTED', 'CANCELED')),
    REGISTER DATETIME NOT NULL DEFAULT GETDATE(),
	ID_SERVICE INT NOT NULL,
    FOREIGN KEY (ID_SERVICE) REFERENCES SERVICES(ID)
);
GO

INSERT INTO SERVERS (ADRESS, STATUS, ENABLED)
VALUES 
('192.168.1.10', 'Online', 'Yes'),
('192.168.1.11', 'Offline', 'No'),
('192.168.1.12', 'Online', 'Yes'),
('192.168.1.13', 'Maintenance', 'No'),
('192.168.1.14', 'Online', 'Yes');

INSERT INTO SERVICES (DESCRIPTION, STATUS, ENABLED, ID_SERVER)
VALUES 
('SQL Server', 'Running', 'Yes', 1),
('IIS Web Server', 'Stopped', 'No', 2),
('Windows Update', 'Running', 'Yes', 3),
('Firewall Service', 'Running', 'Yes', 4),
('Print Spooler', 'Stopped', 'No', 5);
